<a href="https://colab.research.google.com/github/Borii1/Biography/blob/main/Data_Analysis_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Analysis with Python

In [2]:
from google.colab import files
uploaded = files.upload()

Saving ELNIDO_CORON_JANUARY 2026.xlsx to ELNIDO_CORON_JANUARY 2026.xlsx

In [3]:
import pandas as pd

In [5]:
df = pd.read_excel("ELNIDO_CORON_JANUARY 2026.xlsx")

In [9]:
import pandas as pd

df = pd.read_excel("ELNIDO_CORON_JANUARY 2026.xlsx", skiprows=5)

print(df.columns)
df.head()

Index(['Unnamed: 0', 'Ticket No.', 'Name of Passengers', 'Age/Gen',
       'Contact No.', 'Category', 'Accommodation', 'Cot No.', 'Date Booked',
       'By', 'Remarks', 'Amount'],
      dtype='object')

,Unnamed: 0,Ticket No.,Name of Passengers,Age/Gen,Contact No.,Category,Accommodation,Cot No.,Date Booked,By,Remarks,Amount
0,1,6955C0B60D876,"AGARWAL, HARSHIT",29/M,6399999999999,Adult,Open Air,20G,2026-01-01 08:32:00,Jom_Julien,AYAHAY,2800
1,2,6955D248EB4E7,"ALBAY, WILLIAM",41/M,6399999999999,Adult,Aircon,6K,2026-01-01 09:47:00,Jom_Julien,AYAHAY,2800
2,3,6955D5739EAF8,"ALBERICH, GRANT",30/M,6399999999999,Adult,Aircon,13F,2026-01-01 10:01:00,Jom_Julien,AYAHAY,2800
3,4,6952420612D67,"ANANIEV, ZDRAVKO",55/F,6399999999999,Adult,Aircon,3F,2025-12-29 16:55:00,Jom_Julien,ROCK N ROLL,2800
4,5,6955D1BED8239,"ANTONINI, LUDOVICA",33/F,6399999999999,Adult,Aircon,11G,2026-01-01 09:45:00,Jom_Julien,AYAHAY,2800

In [10]:
df[['Age','Gender']] = df['Age/Gen'].str.split('/', expand=True)

df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

df.head()

,Unnamed: 0,Ticket No.,Name of Passengers,Age/Gen,Contact No.,Category,Accommodation,Cot No.,Date Booked,By,Remarks,Amount,Age,Gender
0,1,6955C0B60D876,"AGARWAL, HARSHIT",29/M,6399999999999,Adult,Open Air,20G,2026-01-01 08:32:00,Jom_Julien,AYAHAY,2800,29,M
1,2,6955D248EB4E7,"ALBAY, WILLIAM",41/M,6399999999999,Adult,Aircon,6K,2026-01-01 09:47:00,Jom_Julien,AYAHAY,2800,41,M
2,3,6955D5739EAF8,"ALBERICH, GRANT",30/M,6399999999999,Adult,Aircon,13F,2026-01-01 10:01:00,Jom_Julien,AYAHAY,2800,30,M
3,4,6952420612D67,"ANANIEV, ZDRAVKO",55/F,6399999999999,Adult,Aircon,3F,2025-12-29 16:55:00,Jom_Julien,ROCK N ROLL,2800,55,F
4,5,6955D1BED8239,"ANTONINI, LUDOVICA",33/F,6399999999999,Adult,Aircon,11G,2026-01-01 09:45:00,Jom_Julien,AYAHAY,2800,33,F

In [11]:
df['Gender'] = df['Gender'].map({
    'M': 'Male',
    'F': 'Female'
})

In [12]:
df = df.drop(columns=['Age/Gen'])

In [13]:
df.to_excel("cleaned_passengers.xlsx", index=False)

In [14]:
from google.colab import files
files.download("cleaned_passengers.xlsx")